### ISSUE TITLE
Japan_QAcommunity.md の改善

### ISSUE THREAD

**Issue by nihonbuson** [yusuke-yamashita/memo#3]
書き換えてみたけど、なぜかPushできなかったので、Issueにペタッと貼っときます。

# 日本のQAコミュニティに対する私見

## 目的

この文章は、日本に馴染みのないQAオーガナイザーに日本のQAコミュニティの現状を伝えるための文章です。  
特に、Japan Test Communityに対する説明を想定しています。  

私の意図としては、「日本の文化に合わなければやるな」ではなく、「知る気があるのに、誰も教えていないのは勿体無い」です。  
現状、日本語ネイティブスピーカー以外に十分に情報を与えているとは言えません。  

ですので、本文書を書いているやまずんの観測範囲内でお知らせできること記載します。  

これは日本人の総意ではなく、あくまでやまずんの私見であることをご留意ください。  

コメントや指摘は大歓迎です！  

## 日本のQAイベントの現在

日本のソフトウェアQAイベント、イベントには以下があります。  

- JaSST
- SQiPシンポジウム
- テスト設計コンテスト
- WACATE
- テスト自動化カンファレンス
- and more

### JaSST

JaSSTは日本の各地で開催されており、11地域程度で開催されています。  
つまり、ほぼ毎月どこかで開催されているということです。  
これらはそれぞれ50人程度から多くて2300人程度まで動員しています。  

JaSSTは安くて数千円から参加できます。  
なので、海外のカンファレンスと比べると、参加費用が安いという現状があるように思えます。  

公式サイトは https://www.jasst.jp/  

### SQiPシンポジウム

SQiPシンポジウムは毎年9月ごろに開催されています。  
チュートリアルが1日と発表が2日あります。  
最近は分かりませんが、コロナ禍前は500名程度が参加していた年もありました。  

価格は5万円弱です。  

公式サイトは https://www.juse.jp/sqip/symposium/  

### WACATE
半年に1度、東京近郊で開催されます。  
1泊2日で行われ、プログラムはほとんどがワークショップで構成されています。  

価格は、宿泊費・食費込みで3万円弱です。  

公式サイトは https://wacate.jp/  

### テスト自動化カンファレンス
1年に1度、コロナ禍前は東京で、コロナ禍後はオンラインで開催されます。  
日本での自動テストの事例や知見が数多く紹介されます。  
価格は無料です。  

テスト自動化研究会というコミュニティが主催となっています。  
公式サイトは https://sites.google.com/site/testautomationresearch/  

### 自動化以外の面にも注目している傾向が強い
日本のQAイベントの特徴として、「技術的」とはコンピューターを使ったり、ツールを使うだけでなく、仕事の仕方や工夫も「技術的」と捉えられる傾向にあると思います。  

#### テスト設計コンテスト
特に「テスト設計コンテスト」は顕著だと思います。  
テスト設計コンテストは、「何をテストすべきか」「どうテストケースを作っていくべきか」「テストの全体像はどうあるべきか」などを検討し、競い合うイベントです。  

#### テスト自動化研究会によるテスト自動化の8原則
テスト自動化研究会では[「テスト自動化の8原則」](https://sites.google.com/site/testautomationresearch/test_automation_principle)という発表をしています。この中で、「特にテスト分析、テスト設計が適切に行われていないテスト」に対しての懸念を表明しています。  

テスト設計コンテストとテスト自動化の8原則で共通している点として、「ツールを上手く使う」「自動化する」ではなく、人の頭で考えて、工夫して、正解のない中で正解を探す、という側面を持っています。  
そういったことを重要視してきたQAコミュニティの経緯があります。

### お互いのイベントを尊重し、高めていく文化がある
単独で行わず、お互いのイベントの中で知見を与えながら、共にイベントの価値を高めていく文化があります。  
知見を与えずに、一方的に自分のイベントの宣伝をすることはありません。  

#### JaSSTの場合
テストのワークショップをWACATEの実行委員が企画することがあります。  
テスト設計コンテストの審査委員がテスト設計についての講義を行ったりもします。  

#### WACATEの場合
ワークショップを通じて学んだテスト設計のスキルを試す場としてテスト設計コンテストを紹介することがあります。  

WACATEの参加経験者や実行委員が、後のテスト設計コンテストの審査員になったりしています。  

#### イベント間の連携
JaSST、SQiPシンポジウム、WACATE、テスト設計コンテスト、テスト自動化カンファレンスといった主要のQAイベントは、お互いに事前に共有して、イベント開催日が被らないようにしています。  

## 日本のQAや開発者が多く参加する海外カンファレンス
- Agile Testing Days
  - 最近では毎年5名ほどが参加しています
  - Agile Testing Daysの参加報告会もほぼ毎年行われています
- Seleniumカンファレンス
  - 毎年数名が参加しています
  - 日本で開催した実績もあります(SeleniumConf Tokyo 2019)
- ICST
  - 毎年数名が参加しています
  - 日本で開催した実績もあります(ICST 2017)
    - https://www.aster.or.jp/conference/icst2017/index.html
- EuroSTAR Conference
  - 毎年数名が参加しています

## TQMの成り立ち

**やまずんには手に追えないので誰か考えて欲しい**

**Comment by yusuke-yamashita** [comment]
多謝！
マージしておきました！
